### PR TITLE
feat: fuzion web v1 implemented

### PR DESCRIPTION
**Pull request by Shaharyar-saleem**

### CODE REVIEW

**Review by bobachef — CHANGES_REQUESTED** [review]
fix white space on the bottom

**Comment by Shaharyar-saleem** [comment]
> fix white space on the bottom

fixed

**Comment by Shaharyar-saleem** [comment]
I have aligned the content in the center but I was getting issues when I apply animation in the bottom coin logos, logos disappear, therefore, for now, I just removed the AOS animation from the bottom coin logos

**Review by bobachef — APPROVED** [review]
lgtm

**Pull request merged**
